---
title: "Data, Design, and Digital Humanities"
author: "R. C. Alvarado"
format: html
editor: visual
jupyter: python3
bibliography: references.bib
---

# Abstract

Introduce concept of design, describe its current state of misrecognition, and point to how DH is on it.

# Introduction

The data science body of knowledge (DSBOK) may be divided into five broad areas: analytics, systems, design, value, and practice. These are defined below:

1.  Analytics
2.  Systems
3.  Design
4.  Value
5.  Practice

These areas are elements of an invariant model derived from the the image of the pipeline that dominates discourse about the definition of data science. For a theoretical justification and more complete description of this model, see [@alvarado2022].

For purposes of this essay, it is helpful to recall that the data science pipeline may be thought of as an *arc*, in which the pre- and post-processing segments mirror each other and combine to form structural areas.

Among these areas, the least well understood is [design]{style="keyword"}.

-   The area of design encompasses the knowledge shared by both data modeling (which belongs to the pre-processing segment of the pipeline) and visualization (which belongs to the post-processing segment).

-   Design is most closely associated with the field of human-computer interaction (HCI), but also the fields data modeling and ontology design. Because the latter tend to be identified with database management, which belongs to [systems]{style="keyword"}, design tends not to be recognized as a separate field.

To understand design on its own terms, consider the communicative relationship between humans and machines and how this relationship maps onto the pipeline of data science. On the pre-processing side, the work of data science is focused on converting information as captured and understood by humans --- for example, in textual or analog form --- into forms that can be processed by machines. We call machine processable information *data*. On the post-processing side, data science is focused on converting the results of esoteric modeling and analysis into humanly intelligible forms through the work of visualization and digital storytelling.

Abstractly, we may represent these moments as $H \rightarrow M$ and $M \rightarrow H$. The following table describes some of the concepts and practices currently associated with each:

-   HM

    -   Visual modeling: ER, UML
    -   Verbal classification: taxonomies, ontologies

-   MH

    -   Interactive visualization

    -   Digital storytelling

    # Theorization

    -   Informating
