---
title: "Introduction"
author: "R. C. Alvarado"
format: html
editor: visual
jupyter: python3
bibliography: references.bib
---

# Introduction

The data science body of knowledge ([DSBOK]{.acronym}) may be divided into five broad areas: [analytics]{.keyword}, [systems]{.keyword}, [design]{.keyword}, [value]{.keyword}, and [practice]{.keyword}. The table below gives a sample of activities associated with each area.

+---------------+--------------------------------------------------------------------------------------------------------------------+
| AREA          | ACTIVITY                                                                                                           |
+===============+====================================================================================================================+
| **Analytics** | Statistical modeling, algorithmic modeling, simulations, pattern discovery, data reduction, etc.                   |
+---------------+--------------------------------------------------------------------------------------------------------------------+
| **Systems**   | Programming, software development, ML ops, cloud computing, high-performance computing, etc.                       |
+---------------+--------------------------------------------------------------------------------------------------------------------+
| **Design**    | Data modeling for databases, ontology making, visualization, data storytelling, etc.                               |
+---------------+--------------------------------------------------------------------------------------------------------------------+
| **Value**     | Ethics, scientific research formulation, business value framing, strategic planning, etc.                          |
+---------------+--------------------------------------------------------------------------------------------------------------------+
| **Practice**  | Project management, cross-functional team building, information architecture, connection to domain knowledge, etc. |
+---------------+--------------------------------------------------------------------------------------------------------------------+

: The Five Areas of Data Science

These areas are elements of an invariant model derived from the image of the data processing *pipeline* that has dominated discourse about the definition of data science since its beginnings in the 1950s. This model is called the 4+1 model of data science. For a theoretical justification and brief historical overview of this model, see [@alvarado2022]. For purposes of this essay, it is helpful to recall that the data science pipeline may be thought of as an *arc*, in which the pre- and post-processing segments mirror each other and combine to form structural areas (see [Appendix](appendix.html "Appendix")).

# Design

Among the five areas of data science, the least well understood is design. This area encompasses the knowledge shared by both data modeling for databases (which belongs to the pre-processing segment of the pipeline) and visualization (which belongs to the post-processing segment). Design is most closely associated with the field of human-computer interaction ([HCI]{.acronym}), but also the fields of data modeling for databases and ontology design, which tend to be associated with with database and information management (which belong to systems). Because of these disparate associations, design tends not to be recognized as a separate field. One result of this lack of recognition is the under-theorization of the area.

To understand design on its own terms, consider the communicative relationship between humans and computational machines and how this relationship maps onto the pipeline of data science. On the pre-processing side, the work of data science is focused on converting information as captured and understood by humans --- for example, in textual or analog form --- into forms that can be processed by machines. (We call machine processable information *data*; more on this below.) On the post-processing side, data science is focused on converting the results of esoteric modeling and analysis into more humanly intelligible forms through the work of visualization and digital storytelling.

Formally, we may represent these moments as $H \rightarrow M$ and $M \rightarrow H$ (or $H \leftarrow M$). The following table describes some of the artifacts and practices currently associated with each:

+----------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| Pre-processing ($H \rightarrow M$)                                                                                   | Post-processing ($M \rightarrow H$)                                                                                              |
+======================================================================================================================+==================================================================================================================================+
| [Visual modeling]{.underline}: E-R diagrams, [UML](https://www.uml.org/) diagrams, etc.                              | [Interactive visualization]{.underline}: Dashboards, user-facing databases, etc.                                                 |
|                                                                                                                      |                                                                                                                                  |
| [Verbal classification]{.underline}: taxonomies and ontologies (e.g. RDF, SKOS, OWL), Knowledge Representation, etc. | [Static visualization]{.underline}: infographics, posters, embedded figures and charts, etc.                                     |
|                                                                                                                      |                                                                                                                                  |
| [Domain-specific models]{.underline}: protein models, text models, etc.                                              | [Digital storytelling]{.underline}: integration of visual and verbal elements into narrative, cinematic, or immersive form, etc. |
|                                                                                                                      |                                                                                                                                  |
|                                                                                                                      | [Data product design]{.underline}: user interface and interaction design of data-driven software products for end-users, etc.    |
+----------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+

: Two Moments of Design

What is common to these activities? In both moments, the knowledge worker develops and applies a formal language, verbal or visual, to create a functional *representation* that mediates between cognitive structures of humans and those of machines.[^introduction-1] These representations are of two kinds. The first kind are representations of the world, as understood by humans, to the computational and mathematical machinery that will process the represented information. The second kind are representations of the results of mathematical modeling and discovery to the world, i.e. to non-specialist stakeholders and to users of data products. Common to both cases are representations that mediate between the strict demands of mechanical processing and the more labile requirements of human cognition.

[^introduction-1]: The idea that machines may be thought of having *cognition* is implied by the field of artificial intelligence. For a good theorization of machine (and other non-human) forms of cognition, see [@hayles2017].

Given the focus of design on representation, what are some specific characteristics of representation in this context? A full answer to this question is not possible here for two reasons. First, the topic itself is broad and will eventually require volumes for a systematic treatment, as we can expect with any well-developed idea within a body of knowledge. Second, and as noted, the topic is under-theorized. Although some important contributions have been made to the field, especially from the field of [HCI]{.acroynym}, it remains understudied, especially in the uniform manner implied by the 4+1 model of data science.

Here we may note the following features shared by both the pre- and post-processing moments of design.

+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Formal**           | Representations in the design space tend to be formal, in the sense of grammar-driven. For example, ER diagrams are constructed using one of many visual grammars. In the area of visualization and communication, representations may follow more or less formal grammars, ranging from the grammar of graphics [@wilkinson2012; @wickham2010] to guidelines and principles [@tufte2006; @tufte1985; @tufte1991].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Non-quantitative** | Although formal, typically design grammars are not quantitative per se. They focus on structural patterns and relationships that ground quantitative modeling. Indeed, the work of designing data structures in the pre-processing segment of the pipeline lays the groundwork for measurement-based quantitative reasoning in the modeling phases. Similarly, visualizations of the results of statistical models will translate numerically expressed quantities into qualitatively grasped sensory channels, such as color, size, shape, and position.                                                                                                                                                                                                                                                                                                                                                                                          |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Logical**          | Design grammars are more or less logical, in the sense of making explicit relationships that may be used to make inferences. For example, the relations (i.e. edges) in an ER diagram define the possible propositions that may be constructed from a data set (which are often expressed in [SQL]{.acronym}). Less rigidly, the design of an infographic, such as Minard's map of Napoleon's Russian campaign, may suggest causal relations by the judicious positioning of graphical elements [@mizono2017].                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Aesthetic**        | In addition of deductive reasoning, representations of data in the design space often rely on humans' aesthetic perception and judgement to convey meaning. (Here, aesthetics refers to sensory perception as well as the perception of emergent properties such as beauty.) The disproportionate reliance of the human brain on visual information is well known, and representations of data exploit this reliance either implicitly or explicitly through the use of elements such as "contrast, balance, emphasis, movement, white space, proportion, hierarchy, repetition, rhythm, pattern, unity, and variety" [@chapman2018: terms lower-cased].                                                                                                                                                                                                                                                                                           |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Reductive**        | All representations to be effective must be reduced representations --- they select and foreground a small set of features from the high-dimensional space of experience. They are not intended to capture all of reality but a salient subset of reality relevant to a context and a task. As Borges wrote in "Funes the Memorius," "To think is to forget differences, generalize, make abstractions" [@borges1964: p. 66].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Double-voiced**    | Given their role in mediating between human cognition and computational machinery, representations in this space operate along two axes of meaning --- the human and machine. That is, they are often meant to be readable by both humans and machines. This is actually an explicit design goal of SGML (and by descent XML), which was developed to make machine processable text intelligible to humans as well as machines. As Goldfarb, the inventor of SGML says, "XML is a data representation that has the characteristics of a document ... \[you can\] process it as data --- by first parsing it to extract the data --- or you can present it the way you would a document" [@floydConversationCharlesGoldfarb1998]. To be sure, this is not so true in the case of infographics and data stories. Nevertheless, these representations will always contain elements that are directly traceable to mathematical or algorithmic models. |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Playful**          | Finally, the area of design always involves a kind of play, since the formalisms adopted are never the only ones possible for a specific task. By play, we mean that there there is always some choice and interpretation involved in choosing and developing a representation, and that this process is not reducible to a mechanical procedure. In other words, producing effective representations in the design space involves is a combination of science and art.                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

# Data as Representation

A special case of $H \rightarrow M$ representation is *data*, as commonly understood by data scientists and data analysts. Although in general usage the word may take on a wide range of meanings, in practice it refers to what is often called "structured information," where structure typically means *tabular* structure. The content of such tables is typically populated by discrete numbers and categories. It follows that an essential component of design is the literal creation of data, as a form of representation.

# Theorization

-   Frye!
-   Licklider
-   Crawford
-   Naur
-   Suchman
-   Zuboff (Informating)
-   Latour
-   Manovich

# Digital Humanities

-   Unsworth and KR
-   Review of literature in major journals

# Areas

## Models of Text

## Models and Categories

## Models of Culture and History

-   Schema
-   HEML

## Visualization of Cultural Things

## Genres of Visualization

## Critical Evaluation of Methods

# Concepts

## Data

## Impedance

## Transductive Plasma
